function helperPredViz 
% This function is only intended to support wavelet deep learning examples.
% It may change or be removed in a future release.

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: ./predClassProb.txt

% Auto-generated by MATLAB on 25-Oct-2019 17:27:31

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
predClassProb = readtable("predClassProb.txt", opts);


%% Clear temporary variables
clear opts

%% Plot the results 

classNames = {'16QAM';'B-FM';'BPSK';'CPFSK';'DSB-AM';'GFSK';'PAM4';'SSB-AM'};
figure
bar( predClassProb.VarName1) 
set(gca, 'XTickLabel' , classNames)
xlabel('Class Labels')
ylabel('Probability')
title('Modulation Classification Output') 
axis tight; 
grid on; 
end


