% -----------------------------------------------------------------------
% -----------------------------------------------------------------------
% -----------------------------------------------------------------------
% Build and analyze RF environment
clear all

% -----------------------------------------------------------------------
% simulation control parameters
sim.nThrow   = 1 ;
sim.oversamp = 2 ;
sim.maxStartDelay = 80000 ;

% Overall environmental and system parameters
sys.nAnt          = 1 ;
sys.bandwidthBins = 10^3 * sim.oversamp ; % unitless frequency bins

% -----------------------------------------------------------------------
%load envParams
envParams

% -----------------------------------------------------------------------
% build environment
%

wave = env{8} ;

nPulses = floor(wave.critSamps...
               /wave.details.nPulseToPulseCrit) ;
            
% baseSRaw = ...
%                 chirp(wave.bwBins, ...
%                 wave.details.nCritPulseSamp, ...
%                 wave.details.nPulseToPulseCrit, ...
%                 nPulses, ...
%                 wave.details.freqOvSamp) ;

baseSRaw = ...
                chirp( ...
                wave.details.nCritPulseSamp, ...
                wave.details.nPulseToPulseCrit, ...
                nPulses, ...
                wave.details.freqOvSamp) ;
case wave.details.chipSign

% need to add channel here
           baseS = baseSRaw;

           cenFreqBin = 100 ;

           %reband(baseS, sysBWbins, targetBWbins, targetIFbin,ovSamp)

           % PBS{throwIn}.sig = ...
           %     reband(baseS, ...
           %     sys.bandwidthBins, ...
           %     wave.bwBins * sim.oversamp * wave.details.freqOvSamp , ...
           %     cenFreqBin, ...
           %     1) ;
           PBS{1}.sig = ...
               reband(baseS, ...
               sys.bandwidthBins, ...
               wave.bwBins* wave.details.freqOvSamp, ...
               cenFreqBin, ...
               1) ;


pspectrum(PBS{1}.sig, sim.oversamp*10^9,'spectrogram',...
    'Leakage',1,'OverlapPercent',90, ...
    'MinThreshold',-20,'FrequencyLimits',[-.5*10^9 .5*10^9]);

disp('done')

